# -*- coding: utf-8 -*-
"""Prompt-driven art data analysis-2-Koo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKmxw5-IF2Q5zv9OaGRecU8W9zsyCj8s
"""

# 작품 데이터 수집 예시
import requests
import pandas as pd

# 1. 키워드 검색
params = {"q": "landscape", "artistOrCulture": True}
search_url = "https://collectionapi.metmuseum.org/public/collection/v1/search"
response = requests.get(search_url, params=params).json()
object_ids = response.get("objectIDs", [])[:20]

# 2. 작품 상세정보 가져오기
artworks = []
for oid in object_ids:
    obj = requests.get(f"https://collectionapi.metmuseum.org/public/collection/v1/objects/{oid}").json()
    if obj.get("primaryImageSmall"):
        artworks.append({
            "title": obj["title"],
            "artist": obj["artistDisplayName"],
            "year": obj["objectDate"],
            "medium": obj["medium"],
            "image": obj["primaryImageSmall"]
        })

df = pd.DataFrame(artworks)
df.head()

import requests
import pandas as pd

# 사용자 주제 입력
theme = "flowers"  # 혹은 input("Enter your theme: ")

# 검색
search_url = "https://collectionapi.metmuseum.org/public/collection/v1/search"
params = {"q": theme, "artistOrCulture": True}
res = requests.get(search_url, params=params).json()
object_ids = res.get("objectIDs", [])[:30]

# 상세 수집
artworks = []
for oid in object_ids:
    data = requests.get(f"https://collectionapi.metmuseum.org/public/collection/v1/objects/{oid}").json()
    if data.get("primaryImageSmall"):
        artworks.append({
            "title": data["title"],
            "artist": data["artistDisplayName"],
            "year": data["objectDate"],
            "medium": data["medium"],
            "image": data["primaryImageSmall"]
        })

df = pd.DataFrame(artworks)
df.to_csv("artworks.csv", index=False)

df

"""## Colab에 app.py 파일 생성"""

with open("app.py", "w") as f:
    f.write('''
import streamlit as st
import pandas as pd

st.set_page_config(page_title="Virtual Art Exhibition", layout="wide")
st.title("🎨 My Virtual Art Exhibition")
st.caption("Powered by The Met Open Access API")

theme = "flowers"
st.subheader(f"Curated Theme: {theme.capitalize()}")

df = pd.read_csv("artworks.csv")

for i, row in df.iterrows():
    st.image(row["image"], width=300)
    st.markdown(f"**{row['title']}** by *{row['artist']}*")
    st.caption(f"{row['year']} · {row['medium']}")
    st.markdown("---")

st.markdown("📝 _This exhibition explores the symbolic use of flowers in art history..._")
''')

# Commented out IPython magic to ensure Python compatibility.
# 1. Colab에서 Git 설치 및 사용자 정보 등록 (최초 1회)
!git config --global user.name "jahwankoo"
!git config --global user.email "jahwankoo@email.com"

# 2. GitHub 토큰 발급 받아 사용
# https://github.com/settings/tokens → "classic token" 발급 → repo 권한 체크

# 3. Colab에 app.py와 artworks.csv 만든 뒤, GitHub에 업로드
!git clone https://github.com/jahwankoo/virtual-exhibition.git
# %cd virtual-exhibition

# 복사한 파일 이동
!cp /content/app.py .
!cp /content/artworks.csv .

# GitHub에 업로드
!git add .
!git commit -m "Add app and artwork data"
!git push https://jahwankoo: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@github.com/jahwankoo/virtual-exhibition.git